apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      run: example
    name: example
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: example
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: example
      spec:
        containers:
        - image: node-microsvc-example:latest
          imagePullPolicy: Never
          name: example
          ports:
          - containerPort: 3000
            protocol: TCP
#          env:
#          - name: NODE_ENV
#            value: "office"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: example
    name: example
    namespace: default
  spec:
    selector:
      run: example
    sessionAffinity: None
    type: NodePort
    ports:
    - port: 3000
      name: http
#    - name: http
#      port: 3000
#      targetPort: 80
#      protocol: TCP
#  status:
#    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""